Update Yaml with snyk auth

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -118,6 +118,28 @@ jobs:
             sudo snyk --version
           fi
 
+      - name: Authenticate Snyk CLI
+        run: snyk auth ${{ secrets.SNYK_TOKEN }}
+
+      - name: Verify Snyk Authentication
+        run: |
+          sudo snyk auth ${{ secrets.SNYK_TOKEN }}
+          if [ $? -ne 0 ]; then
+            echo "Snyk authentication failed"
+            exit 1
+          fi
+
+      # Step 3: List Snyk organizations
+      - name: List Snyk organizations
+        run: sudo snyk org list
+
+      - name: List Snyk Organizations
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        run: |
+          echo "Listing Snyk organizations..."
+          curl -s -H "Authorization: token $SNYK_TOKEN" https://api.snyk.io/v1/orgs | jq '.data[] | {name: .attributes.name, id: .id}'
+
       # Step 8: Snyk Security Scans for Java
       - name: Snyk Security Scans
         run: snyk test --org=Vinay187534 --project-name='EKS-Terraform-GitHub-Actions' --file=./pom.xml --debug
