Update Frontend_CICD.yml

diff --git a/.github/workflows/Frontend_CICD.yml b/.github/workflows/Frontend_CICD.yml
--- a/.github/workflows/Frontend_CICD.yml
+++ b/.github/workflows/Frontend_CICD.yml
@@ -11,187 +11,187 @@ on:
         options:
           - frontend
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
+  #   build:
+  #     runs-on: ubuntu-latest
+  #     permissions:
+  #       contents: write
 
-    env:
-      COVERAGE_THRESHOLD: 75 # Set your desired coverage threshold here
-      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      AWS_REGION: ${{ secrets.AWS_REGION }}
-      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
-      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
-      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+  #     env:
+  #       COVERAGE_THRESHOLD: 75 # Set your desired coverage threshold here
+  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #       AWS_REGION: ${{ secrets.AWS_REGION }}
+  #       DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
+  #       DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+  #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.G_TOKEN }}
+  #     steps:
+  #       - name: Checkout repository
+  #         uses: actions/checkout@v3
+  #         with:
+  #           token: ${{ secrets.G_TOKEN }}
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: "18"
+  #       - name: Set up Node.js
+  #         uses: actions/setup-node@v3
+  #         with:
+  #           node-version: "18"
 
-      - name: Cache Node.js modules
-        id: npm-cache
-        uses: actions/cache@v3
-        with:
-          path: ./green-global-initiative-ui/node_modules
-          key: npm-${{ hashFiles('green-global-initiative-ui/package-lock.json') }}
-          restore-keys: |
-            npm-
+  #       - name: Cache Node.js modules
+  #         id: npm-cache
+  #         uses: actions/cache@v3
+  #         with:
+  #           path: ./green-global-initiative-ui/node_modules
+  #           key: npm-${{ hashFiles('green-global-initiative-ui/package-lock.json') }}
+  #           restore-keys: |
+  #             npm-
 
-      - name: Install dependencies
-        working-directory: ./green-global-initiative-ui
-        run: npm install
+  #       - name: Install dependencies
+  #         working-directory: ./green-global-initiative-ui
+  #         run: npm install
 
-      - name: Install Angular CLI locally
-        working-directory: ./green-global-initiative-ui
-        run: npm install @angular/cli --save-dev
+  #       - name: Install Angular CLI locally
+  #         working-directory: ./green-global-initiative-ui
+  #         run: npm install @angular/cli --save-dev
 
-      - name: Build the project
-        working-directory: ./green-global-initiative-ui
-        run: npm run build
+  #       - name: Build the project
+  #         working-directory: ./green-global-initiative-ui
+  #         run: npm run build
 
-      - name: Run Tests in Headless Mode
-        working-directory: ./green-global-initiative-ui
-        run: |
-          npm test -- --browsers=ChromeHeadless --watch=false --code-coverage --karma-config=karma.conf.js --reporters junit || true
+  #       - name: Run Tests in Headless Mode
+  #         working-directory: ./green-global-initiative-ui
+  #         run: |
+  #           npm test -- --browsers=ChromeHeadless --watch=false --code-coverage --karma-config=karma.conf.js --reporters junit || true
 
-      - name: Extract Coverage Percentage
-        id: coverage
-        working-directory: ./green-global-initiative-ui
-        run: |
-          # Run tests and capture the output
-          TEST_OUTPUT=$(npm test -- --browsers=ChromeHeadless --watch=false --code-coverage --karma-config=karma.conf.js --reporters junit || true)
+  #       - name: Extract Coverage Percentage
+  #         id: coverage
+  #         working-directory: ./green-global-initiative-ui
+  #         run: |
+  #           # Run tests and capture the output
+  #           TEST_OUTPUT=$(npm test -- --browsers=ChromeHeadless --watch=false --code-coverage --karma-config=karma.conf.js --reporters junit || true)
 
-          # Extract the Lines coverage percentage from the output
-          COVERAGE=$(echo "$TEST_OUTPUT" | grep -Eo 'Lines\s*:\s*[0-9.]+%' | awk '{print $3}' | sed 's/%//')
+  #           # Extract the Lines coverage percentage from the output
+  #           COVERAGE=$(echo "$TEST_OUTPUT" | grep -Eo 'Lines\s*:\s*[0-9.]+%' | awk '{print $3}' | sed 's/%//')
 
-          if [ -z "$COVERAGE" ]; then
-            echo "Error: Could not extract coverage percentage."
-            exit 1
-          else
-            echo "Extracted coverage: $COVERAGE%"
-            echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
-          fi
+  #           if [ -z "$COVERAGE" ]; then
+  #             echo "Error: Could not extract coverage percentage."
+  #             exit 1
+  #           else
+  #             echo "Extracted coverage: $COVERAGE%"
+  #             echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
+  #           fi
 
-      - name: Fail if code coverage is below threshold
-        run: |
-          if [ -z "$COVERAGE" ]; then
-            echo "Error: COVERAGE variable is not set."
-            exit 1
-          fi
-          if (( $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
-            echo "Code coverage is below the threshold of $COVERAGE_THRESHOLD%"
-            exit 1
-          else
-            echo "Code coverage is $COVERAGE%, which meets the threshold of $COVERAGE_THRESHOLD%"
-          fi
+  #       - name: Fail if code coverage is below threshold
+  #         run: |
+  #           if [ -z "$COVERAGE" ]; then
+  #             echo "Error: COVERAGE variable is not set."
+  #             exit 1
+  #           fi
+  #           if (( $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
+  #             echo "Code coverage is below the threshold of $COVERAGE_THRESHOLD%"
+  #             exit 1
+  #           else
+  #             echo "Code coverage is $COVERAGE%, which meets the threshold of $COVERAGE_THRESHOLD%"
+  #           fi
 
-      # Snyk Integration
-      - name: Run Snyk to check for vulnerabilities
-        working-directory: ./green-global-initiative-ui
-        run: |
-          npm install -g snyk
-          snyk test --severity-threshold=high
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+  #       # Snyk Integration
+  #       - name: Run Snyk to check for vulnerabilities
+  #         working-directory: ./green-global-initiative-ui
+  #         run: |
+  #           npm install -g snyk
+  #           snyk test --severity-threshold=high
+  #         env:
+  #           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
-      - name: Install Trivy
-        run: |
-          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
-          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
-          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
-          sudo apt-get update
-          sudo apt-get install -y trivy
+  #       - name: Install Trivy
+  #         run: |
+  #           sudo apt-get install -y wget apt-transport-https gnupg lsb-release
+  #           wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
+  #           echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
+  #           sudo apt-get update
+  #           sudo apt-get install -y trivy
 
-      - name: Trivy File Scan
-        working-directory: ./green-global-initiative-ui
-        run: trivy fs . --severity HIGH,CRITICAL --ignore-unfixed > trivyfs-frontend.txt
+  #       - name: Trivy File Scan
+  #         working-directory: ./green-global-initiative-ui
+  #         run: trivy fs . --severity HIGH,CRITICAL --ignore-unfixed > trivyfs-frontend.txt
 
-      # step 10: Image Build, scan, and Push to Docker Hub
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-      - name: Docker Build Backend Image
-        run: |
-          docker build -t ${DOCKER_HUB_USERNAME}/frontend:${GITHUB_SHA} ./green-global-initiative-ui
+  #       # step 10: Image Build, scan, and Push to Docker Hub
+  #       - name: Set up Docker Buildx
+  #         uses: docker/setup-buildx-action@v2
+  #       - name: Docker Build Backend Image
+  #         run: |
+  #           docker build -t ${DOCKER_HUB_USERNAME}/frontend:${GITHUB_SHA} ./green-global-initiative-ui
 
-      - name: Trivy Image Scan
-        run: trivy image ${DOCKER_HUB_USERNAME}/frontend:${GITHUB_SHA} --severity HIGH,CRITICAL > trivyimage-frontend.txt
+  #       - name: Trivy Image Scan
+  #         run: trivy image ${DOCKER_HUB_USERNAME}/frontend:${GITHUB_SHA} --severity HIGH,CRITICAL > trivyimage-frontend.txt
 
-      - name: Push Docker Image to Docker Hub
-        run: |
-          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
-          docker push ${DOCKER_HUB_USERNAME}/frontend:${GITHUB_SHA}
+  #       - name: Push Docker Image to Docker Hub
+  #         run: |
+  #           echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
+  #           docker push ${DOCKER_HUB_USERNAME}/frontend:${GITHUB_SHA}
 
-      # OWASP Dependency Check with report generation
-      - name: Run OWASP Dependency Check
-        uses: dependency-check/Dependency-Check_Action@main
-        with:
-          project: "green-global-initiative"
-          scan-path: "./green-global-initiative-ui"
-          format: "ALL"
-          output: "./reports"
-          fail_on_cvss: 7
+  #       # OWASP Dependency Check with report generation
+  #       - name: Run OWASP Dependency Check
+  #         uses: dependency-check/Dependency-Check_Action@main
+  #         with:
+  #           project: "green-global-initiative"
+  #           scan-path: "./green-global-initiative-ui"
+  #           format: "ALL"
+  #           output: "./reports"
+  #           fail_on_cvss: 7
 
-      # Documentation
-      - name: Generate Compodoc documentation
-        working-directory: ./green-global-initiative-ui
-        run: |
-          npx compodoc -p tsconfig.app.json -d documentation
-        continue-on-error: true
+  #       # Documentation
+  #       - name: Generate Compodoc documentation
+  #         working-directory: ./green-global-initiative-ui
+  #         run: |
+  #           npx compodoc -p tsconfig.app.json -d documentation
+  #         continue-on-error: true
 
-      # Upload all reports
-      - name: Upload test results
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-results
-          path: ./green-global-initiative-ui/test-results
+  #       # Upload all reports
+  #       - name: Upload test results
+  #         uses: actions/upload-artifact@v4
+  #         with:
+  #           name: test-results
+  #           path: ./green-global-initiative-ui/test-results
 
-      - name: Upload coverage report
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-report
-          path: ./green-global-initiative-ui/coverage
+  #       - name: Upload coverage report
+  #         uses: actions/upload-artifact@v4
+  #         with:
+  #           name: coverage-report
+  #           path: ./green-global-initiative-ui/coverage
 
-      - name: Upload OWASP Dependency Check reports
-        uses: actions/upload-artifact@v4
-        with:
-          name: dependency-check-reports
-          path: ./reports/*
+  #       - name: Upload OWASP Dependency Check reports
+  #         uses: actions/upload-artifact@v4
+  #         with:
+  #           name: dependency-check-reports
+  #           path: ./reports/*
 
-      - name: Upload Compodoc documentation
-        uses: actions/upload-artifact@v4
-        with:
-          name: compodoc-documentation
-          path: ./green-global-initiative-ui/documentation/*
+  #       - name: Upload Compodoc documentation
+  #         uses: actions/upload-artifact@v4
+  #         with:
+  #           name: compodoc-documentation
+  #           path: ./green-global-initiative-ui/documentation/*
 
-      - name: Upload Trivy scan results
-        uses: actions/upload-artifact@v4
-        with:
-          name: trivy-scan-results
-          path: |
-            ./green-global-initiative-ui/trivyfs-frontend.txt
-            ./trivyimage-frontend.txt
+  #       - name: Upload Trivy scan results
+  #         uses: actions/upload-artifact@v4
+  #         with:
+  #           name: trivy-scan-results
+  #           path: |
+  #             ./green-global-initiative-ui/trivyfs-frontend.txt
+  #             ./trivyimage-frontend.txt
 
-      - name: Update Deployment Image in YAML
-        run: |
-          IMAGE_TAG=${GITHUB_SHA}
-          sed -i "s|image: .*$|image: ${DOCKER_HUB_USERNAME}/frontend:${IMAGE_TAG}|" ./Kubernetes-Manifest-Files/frontend/deployment.yaml
-          git config --global user.email "L001875354@atu.ie"
-          git config --global user.name "vinay187534"
-          git checkout ${GITHUB_REF_NAME}
-          git add ./Kubernetes-Manifest-Files/frontend/deployment.yaml
-          git commit -m "Update frontend image tag to ${IMAGE_TAG}"
-          git push https://${{ secrets.G_TOKEN }}@github.com/${{ github.repository }} HEAD:${GITHUB_REF_NAME}
+  #       - name: Update Deployment Image in YAML
+  #         run: |
+  #           IMAGE_TAG=${GITHUB_SHA}
+  #           sed -i "s|image: .*$|image: ${DOCKER_HUB_USERNAME}/frontend:${IMAGE_TAG}|" ./Kubernetes-Manifest-Files/frontend/deployment.yaml
+  #           git config --global user.email "L001875354@atu.ie"
+  #           git config --global user.name "vinay187534"
+  #           git checkout ${GITHUB_REF_NAME}
+  #           git add ./Kubernetes-Manifest-Files/frontend/deployment.yaml
+  #           git commit -m "Update frontend image tag to ${IMAGE_TAG}"
+  #           git push https://${{ secrets.G_TOKEN }}@github.com/${{ github.repository }} HEAD:${GITHUB_REF_NAME}
 
   deploy-on-EKS:
-    needs: build
+    # needs: build
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
@@ -242,7 +242,7 @@ jobs:
       - name: Deploy Kubernetes Manifests to EKS
         if: env.deployment-exists == 'false'
         run: |
-          echo "🚀 First-time deployment: Applying Kubernetes manifests..."
+          echo "First-time deployment: Applying Kubernetes manifests..."
           kubectl apply -f ./Kubernetes-Manifest-Files/Database/
           kubectl apply -f ./Kubernetes-Manifest-Files/frontend/
           kubectl apply -f ./Kubernetes-Manifest-Files/Frontend-ingress/frontend-ingress.yaml
